name: 'retail_project'
version: '1.0'
config-version: 2
profile: 'retail_project'

# Paths
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled SQL and artifacts go
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Default model configurations
models:
  retail_project:
    +schema: retail   # all models go to retail schema

    staging:
      +materialized: view   # recommended for staging layer

    marts:
      +materialized: table

    dimensions:
      +materialized: table

    fact:
      +materialized: table

# Seeds configuration
seeds:
  retail_project:
    +schema: retail   # seeds also go to retail schema
    +materialized: table