version: 2

sources:
  - name: retail      # this is the source name you use in {{ source(...) }}
  
    schema: postgres_retail # this is the actual schema in your database
    tables:
      - name: orders
      - name: customers
      - name: payments
      - name: order_details
      - name: products